/* Prime Lift — shared page script (generated by build.py). Nav, mobile menu,
   reveal-on-scroll, FAQ accordions and the sticky call bar for inner pages. */
(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const nav=$("#nav"), burger=$("#navBurger"), callbar=$("#callbar");
  const home=!!$(".hero");            /* the home page keeps its own scroll logic */

  if(burger){
    burger.addEventListener("click",()=>{
      const open=document.body.classList.toggle("mnav-open");
      burger.setAttribute("aria-expanded",open?"true":"false");
      burger.setAttribute("aria-label",open?"Close menu":"Open menu");
    });
    $$("#mnav a").forEach(a=>a.addEventListener("click",()=>{ document.body.classList.remove("mnav-open"); burger.setAttribute("aria-expanded","false"); }));
    document.addEventListener("keydown",e=>{ if(e.key==="Escape"&&document.body.classList.contains("mnav-open")) burger.click(); });
  }

  if(!home){
    /* no layout reads inside the handler: just scrollY, which is free */
    let ticking=false;
    function paint(){
      const y=window.scrollY;
      if(nav) nav.classList.toggle("stuck",y>40);
      if(callbar) callbar.classList.toggle("show",y>360);
      ticking=false;
    }
    window.addEventListener("scroll",()=>{ if(!ticking){ ticking=true; requestAnimationFrame(paint); } },{passive:true});
    paint();
  }

  /* reveal */
  const rv=$$(".rv");
  if("IntersectionObserver" in window){
    const io=new IntersectionObserver(es=>es.forEach(e=>{ if(e.isIntersecting){ e.target.classList.add("in"); io.unobserve(e.target); } }),{rootMargin:"0px 0px -8% 0px",threshold:.08});
    rv.forEach(el=>io.observe(el));
  } else rv.forEach(el=>el.classList.add("in"));

  /* FAQ accordions on inner pages (home renders its own) */
  $$("[data-faq]").forEach(host=>{
    host.addEventListener("click",e=>{
      const q=e.target.closest(".faq-q"); if(!q) return;
      const item=q.parentElement, a=item.querySelector(".faq-a"), open=item.classList.contains("open");
      $$(".faq-item",host).forEach(it=>{ it.classList.remove("open"); it.querySelector(".faq-a").style.maxHeight=null; it.querySelector(".faq-q").setAttribute("aria-expanded","false"); });
      if(!open){ item.classList.add("open"); a.style.maxHeight=a.scrollHeight+"px"; q.setAttribute("aria-expanded","true"); }
    });
  });
  window.addEventListener("resize",()=>{ $$(".faq-item.open .faq-a").forEach(a=>{ a.style.maxHeight="none"; const h=a.scrollHeight; a.style.maxHeight=h+"px"; }); });
})();
