/* Prime Lift — shared page script (generated by build.py). Nav, mobile menu,
   reveal-on-scroll, FAQ accordions and the sticky call bar for inner pages. */
(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const nav=$("#nav"), burger=$("#navBurger"), callbar=$("#callbar");
  const home=!!$(".hero");            /* the home page keeps its own scroll logic */

  if(burger){
    const setAcc=(acc,open)=>{ acc.classList.toggle("open",open); acc.querySelector(".macc-t").setAttribute("aria-expanded",open?"true":"false"); };
    burger.addEventListener("click",()=>{
      const open=document.body.classList.toggle("mnav-open");
      burger.setAttribute("aria-expanded",open?"true":"false");
      burger.setAttribute("aria-label",open?"Close menu":"Open menu");
      if(!open) $$(".macc.open").forEach(a=>setAcc(a,false));   /* collapse on close so it reopens tidy */
    });
    /* Courses / Academy accordions inside the mobile menu */
    $$(".macc-t").forEach(t=>t.addEventListener("click",()=>{ const acc=t.parentElement; setAcc(acc,!acc.classList.contains("open")); }));
    $$("#mnav a").forEach(a=>a.addEventListener("click",()=>{ document.body.classList.remove("mnav-open"); burger.setAttribute("aria-expanded","false"); }));
    document.addEventListener("keydown",e=>{ if(e.key==="Escape"&&document.body.classList.contains("mnav-open")) burger.click(); });
    /* rotate a small tablet past the desktop breakpoint with the menu open and the
       sheet hides itself, leaving the scroll lock and the opaque bar behind */
    window.matchMedia("(min-width:1000px)").addEventListener("change",e=>{
      if(e.matches&&document.body.classList.contains("mnav-open")) burger.click();
    });
  }

  if(!home){
    /* no layout reads inside the handler: just scrollY, which is free */
    let ticking=false, navp="";
    /* COMPARISON SWITCH (temporary, mirrors index.html): ?nav=flat = header never
       changes; ?nav=scrim = scroll-driven. Remembered per tab. Remove once decided. */
    const NAVMODE=(()=>{ try{ const q=new URLSearchParams(location.search).get("nav"); if(q) sessionStorage.setItem("navMode",q); return sessionStorage.getItem("navMode")||"scrim"; }catch(e){ return "scrim"; } })();
    function paint(){
      const y=window.scrollY;
      /* header progress 0..1 over the first 160px, eased out so the scrim is
         already there by the time the hero text has moved; drives bar height,
         logo size and the scrim opacity in CSS (--navp) */
      if(nav&&NAVMODE!=="flat"){ const t=Math.min(1,Math.max(0,y/160)), p=(1-(1-t)*(1-t)).toFixed(3); if(p!==navp){ navp=p; nav.style.setProperty("--navp",p); } }
      if(callbar) callbar.classList.toggle("show",y>360);
      ticking=false;
    }
    window.addEventListener("scroll",()=>{ if(!ticking){ ticking=true; requestAnimationFrame(paint); } },{passive:true});
    paint();
  }

  /* reveal */
  const rv=$$(".rv");
  if("IntersectionObserver" in window){
    const io=new IntersectionObserver(es=>es.forEach(e=>{ if(e.isIntersecting){ e.target.classList.add("in"); io.unobserve(e.target); } }),{rootMargin:"0px 0px -8% 0px",threshold:.08});
    rv.forEach(el=>io.observe(el));
  } else rv.forEach(el=>el.classList.add("in"));

  /* FAQ accordions on inner pages (home renders its own) */
  $$("[data-faq]").forEach(host=>{
    host.addEventListener("click",e=>{
      const q=e.target.closest(".faq-q"); if(!q) return;
      const item=q.parentElement, a=item.querySelector(".faq-a"), open=item.classList.contains("open");
      $$(".faq-item",host).forEach(it=>{ it.classList.remove("open"); it.querySelector(".faq-a").style.maxHeight=null; it.querySelector(".faq-q").setAttribute("aria-expanded","false"); });
      if(!open){ item.classList.add("open"); a.style.maxHeight=a.scrollHeight+"px"; q.setAttribute("aria-expanded","true"); }
    });
  });
  window.addEventListener("resize",()=>{ $$(".faq-item.open .faq-a").forEach(a=>{ a.style.maxHeight="none"; const h=a.scrollHeight; a.style.maxHeight=h+"px"; }); });

  /* Photo gallery lightbox. The CSS for this (.gal-zoom, .lb) shipped a while
     back with nothing driving it, so galleries showed a zoom cursor that did
     nothing. Click a figure to open it full size; arrows or swipe-free nav
     buttons to move; Esc or the backdrop to close. Body overflow is the same
     scroll lock the Lenis prevent hook already looks for. */
  (function(){
    const figs=$$(".gal figure"); if(!figs.length) return;
    const svg=d=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'+d+'</svg>';
    const ZOOM=svg('<circle cx="11" cy="11" r="7"/><path d="m20 20-3.6-3.6"/><path d="M11 8.4v5.2"/><path d="M8.4 11h5.2"/>');
    figs.forEach(f=>{ const b=document.createElement("button"); b.type="button"; b.className="gal-zoom"; b.setAttribute("aria-label","View larger"); b.innerHTML=ZOOM; f.appendChild(b); });
    const lb=document.createElement("div");
    lb.className="lb"; lb.setAttribute("role","dialog"); lb.setAttribute("aria-modal","true"); lb.setAttribute("aria-label","Photo");
    lb.innerHTML='<button class="lb-x" type="button" aria-label="Close">'+svg('<path d="M18 6 6 18"/><path d="m6 6 12 12"/>')+'</button>'
      +'<button class="lb-nav lb-prev" type="button" aria-label="Previous photo">'+svg('<path d="m15 18-6-6 6-6"/>')+'</button>'
      +'<button class="lb-nav lb-next" type="button" aria-label="Next photo">'+svg('<path d="m9 18 6-6-6-6"/>')+'</button>'
      +'<figure class="lb-fig"><img alt=""><figcaption class="lb-cap"><span class="idx"></span><i></i><em></em></figcaption></figure>';
    document.body.appendChild(lb);
    const img=$("img",lb), idx=$(".idx",lb), cap=$("em",lb);
    let at=0, last=null;
    const pad=n=>String(n).padStart(2,"0");
    /* currentSrc is whatever the 25vw thumbnail loaded (often the 480 rung), which
       is useless full screen. Take the widest candidate in the srcset instead. */
    function widest(im){
      const ss=im.getAttribute("srcset");
      if(!ss) return im.currentSrc||im.src;
      return ss.split(",").map(x=>x.trim().split(/\s+/))
               .reduce((a,b)=>(parseInt(b[1])||0)>(parseInt(a[1])||0)?b:a)[0];
    }
    function paint(){
      const f=figs[at], src=$("img",f);
      img.src=widest(src); img.alt=src.alt||"";
      idx.textContent=pad(at+1)+" / "+pad(figs.length);
      cap.textContent=(($("figcaption",f)||{}).textContent||"").trim();
    }
    function open(i){ at=i; last=document.activeElement; paint(); lb.classList.add("open"); document.body.style.overflow="hidden"; $(".lb-x",lb).focus(); }
    function close(){ lb.classList.remove("open"); document.body.style.overflow=""; if(last&&last.focus) last.focus(); }
    const go=d=>{ at=(at+d+figs.length)%figs.length; paint(); };
    figs.forEach((f,i)=>f.addEventListener("click",()=>open(i)));
    $(".lb-x",lb).addEventListener("click",close);
    $(".lb-prev",lb).addEventListener("click",e=>{ e.stopPropagation(); go(-1); });
    $(".lb-next",lb).addEventListener("click",e=>{ e.stopPropagation(); go(1); });
    lb.addEventListener("click",e=>{ if(e.target===lb) close(); });
    document.addEventListener("keydown",e=>{
      if(!lb.classList.contains("open")) return;
      if(e.key==="Escape") close();
      else if(e.key==="ArrowLeft") go(-1);
      else if(e.key==="ArrowRight") go(1);
    });
  })();

  /* course pages: the "next start dates" strip is rendered at build time from
     SCHEDULE_RULES in build.py; recompute from today's date so it never goes
     stale between builds. Same rule: next N occurrences of the weekday, from
     tomorrow (booking closes the day before). */
  const MONS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], DOWS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"], SCHED={"closed":{"2026-09-07":"Labor Day"},"full":{}};
  const iso=d=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");
  const bookable=(x,k)=>!SCHED.closed[iso(x)] && !((SCHED.full[iso(x)]||[]).some(f=>f===k||f==="*"));
  $$(".nd-row").forEach(row=>{
    const wd=+row.dataset.wd; if(isNaN(wd)) return;
    const key=row.dataset.book+":"+row.dataset.fmt, links=$$(".nd-date",row);
    const step=+row.dataset.every||7, anchor=row.dataset.anchor||"";
    const d=new Date(); d.setHours(0,0,0,0); d.setDate(d.getDate()+(+row.dataset.lead||1));
    while(d.getDay()!==wd) d.setDate(d.getDate()+1);
    /* biweekly rules are phased off their anchor date, not off today */
    if(anchor&&step!==7){ const p=anchor.split("-").map(Number), a=new Date(p[0],p[1]-1,p[2]); const off=((Math.round((d-a)/864e5)%step)+step)%step; if(off) d.setDate(d.getDate()+(step-off)); }
    const dates=[]; while(dates.length<links.length){ if(bookable(d,key)) dates.push(new Date(d)); d.setDate(d.getDate()+step); }
    links.forEach((a,i)=>{
      const x=dates[i];
      a.href="/book/?book="+row.dataset.book+"&fmt="+row.dataset.fmt+"&date="+iso(x);
      a.textContent=DOWS[x.getDay()]+", "+MONS[x.getMonth()]+" "+x.getDate();
    });
  });
})();

/* GHL live chat widget (Conversation AI). Loaded lazily so it never competes with
   first paint: first scroll / touch / pointer, or 6s idle, whichever comes first. */
(function(){
  if (window.__plChat) return; window.__plChat = 1;
  var done = false;
  function load(){
    if (done) return; done = true;
    var s = document.createElement("script");
    s.src = "https://widgets.leadconnectorhq.com/loader.js";
    s.setAttribute("data-resources-url", "https://widgets.leadconnectorhq.com/chat-widget/loader.js");
    s.setAttribute("data-widget-id", "6a935fa49f17bc64b3251340");
    document.body.appendChild(s);
    ["scroll","pointerdown","touchstart","keydown"].forEach(function(e){ window.removeEventListener(e, load); });
    lift();
  }
  /* On phones the sticky call bar owns the bottom 60px; keep the bubble above it.
     The widget's bubble lives in an open shadow root with inline bottom:20px, and
     the widget REWRITES that inline style every time the chat window closes, so
     setting it once is not enough (the bubble dropped back onto the Book button).
     A stylesheet inside the shadow root with !important beats the inline value
     for good; the offset rides on a CSS variable on the host element. */
  function lift(){
    var tries = 0;
    var cb = document.getElementById("callbar");
    var CSS = "#lc_text-widget,#lc_text-widget--btn{bottom:var(--pl-bottom,20px)!important}";
    function place(){
      var host = document.querySelector("chat-widget"), sr = host && host.shadowRoot;
      var box = sr && sr.getElementById("lc_text-widget"), btn = sr && sr.getElementById("lc_text-widget--btn");
      if (!box || !btn) { if (tries++ < 60) setTimeout(place, 500); return; }
      if (!sr.getElementById("pl-lift")) { var st = document.createElement("style"); st.id = "pl-lift"; st.textContent = CSS; sr.appendChild(st); }
      var mobile = window.innerWidth <= 900, up = mobile && cb && cb.classList.contains("show");
      host.style.visibility = (mobile && !up) ? "hidden" : "visible";
      host.style.setProperty("--pl-bottom", up ? "78px" : "20px");
      if (!host.__plObs) {
        /* if the widget ever rebuilds its shadow tree, put the stylesheet back */
        host.__plObs = new MutationObserver(function(){ if (!sr.getElementById("pl-lift")) place(); });
        host.__plObs.observe(sr, {childList:true});
      }
    }
    place();
    if (cb) new MutationObserver(place).observe(cb, {attributes:true, attributeFilter:["class"]});
    window.addEventListener("resize", place, {passive:true});
  }
  ["scroll","pointerdown","touchstart","keydown"].forEach(function(e){ window.addEventListener(e, load, {passive:true, once:true}); });
  setTimeout(load, 12000);   /* idle fallback; anyone who scrolls or taps gets it immediately */
})();

/* LIVE SEATS. /.netlify/functions/seats counts open cards in the office's own
   Enrollment pipeline (one card = one seat, Lost frees it), so a class fills up
   on the site the moment the 8th student is booked online OR by phone. The
   static lists render first from CLOSED/FULL in build.py; this pass decorates
   every date link on the page (home band, course strips, class-dates tiles)
   and hands the data to /book/ through the pl:seats event. Fails silent. */
(function(){
  var CAP = 8, LOW = 3;
  function keyOf(a){
    var m = (a.getAttribute("href") || "").match(/[?&]book=([a-z]+)&(?:amp;)?fmt=([a-z]+)&(?:amp;)?date=(\d{4}-\d{2}-\d{2})/);
    return m ? m[1] + ":" + m[2] + ":" + m[3] : null;
  }
  function paint(data){
    var taken = data.taken || {}, cap = data.cap || CAP;
    document.querySelectorAll("a.ln-date, a.nd-date, a.date").forEach(function(a){
      var k = keyOf(a); if (!k) return;
      var left = cap - (taken[k] || 0);
      var tile = a.classList.contains("date"), seats = tile && a.querySelector(".seats");
      if (left <= 0) {
        a.classList.add("is-full"); a.setAttribute("aria-disabled", "true"); a.setAttribute("tabindex", "-1"); a.setAttribute("href", "#");
        if (seats) { seats.querySelector("b").textContent = "—"; seats.querySelector("span").textContent = "full"; }
        else if (!a.querySelector(".left")) a.insertAdjacentHTML("beforeend", '<span class="left"> · full</span>');
        return;
      }
      if (seats) {
        seats.querySelector("b").textContent = left; seats.querySelector("span").textContent = left === 1 ? "seat left" : "seats left";
        seats.classList.toggle("low", left <= LOW);
      } else if (left <= LOW && !a.querySelector(".left")) {
        a.insertAdjacentHTML("beforeend", '<span class="left"> · ' + left + " left</span>");
      }
    });
  }
  function go(){
    var url = "/.netlify/functions/seats";
    if (location.protocol === "file:" || /^(127\.0\.0\.1|localhost)$/.test(location.hostname) && location.port !== "8888") return;
    fetch(url, {cache: "no-cache"}).then(function(r){ return r.ok ? r.json() : null; }).then(function(d){
      if (!d || !d.taken) return;
      window.__plSeats = d;
      paint(d);
      document.dispatchEvent(new CustomEvent("pl:seats", {detail: d}));
    }).catch(function(){});
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", go); else go();
})();

/* DESKTOP INERTIA SCROLL. On fine-pointer screens 1000px and up, /js/lenis.min.js
   (vendored, MIT, v1.3.26) eases wheel scrolling and same-page anchor jumps, the
   glide people know from agency sites. Phones, tablets and reduced-motion users
   never download it and keep native scroll-behavior:smooth from site.css.
   The prevent hook keeps native behaviour wherever hijacking would break things:
   any overflowing nested scroller under the pointer (chat log, tables, strips)
   and any body scroll lock (gallery lightbox, mobile menu). Lenis honours each
   target's scroll-margin-top, so anchors land where they do today. */
(function(){
  var mm = window.matchMedia;
  if (!mm || !mm("(pointer:fine)").matches || mm("(prefers-reduced-motion:reduce)").matches || window.innerWidth < 1000) return;
  var s = document.createElement("script");
  s.src = "/js/lenis.min.js"; s.defer = true;
  s.onload = function(){
    if (!window.Lenis) return;
    var lenis = window.__lenis = new Lenis({
      lerp: 0.1, wheelMultiplier: 1, smoothWheel: true, syncTouch: false, anchors: false, autoRaf: true,
      prevent: function(node){
        if (node === document.body) return document.body.style.overflow === "hidden" || document.body.classList.contains("mnav-open");
        if (node.nodeType !== 1 || node === document.documentElement) return false;
        if (node.scrollHeight <= node.clientHeight + 1) return false;
        var o = getComputedStyle(node).overflowY;
        return o === "auto" || o === "scroll";
      }
    });
    /* Same-page anchors: Lenis's own `anchors` option never cancels the browser's
       hash jump, so a click flashed to the target, snapped back and then glided.
       Cancel the jump here and let Lenis ease from where the page is; the hash
       still lands in the URL. Bubble phase, so a link's own handler (FAQ, reel
       arrows, "#" hooks) that preventDefaults keeps winning. */
    document.addEventListener("click", function(e){
      if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
      var a = e.target.closest && e.target.closest("a[href]"); if (!a) return;
      var u; try { u = new URL(a.href); } catch (_) { return; }
      if (u.host !== location.host || u.pathname !== location.pathname || u.hash.length < 2) return;
      var el = document.getElementById(decodeURIComponent(u.hash.slice(1))); if (!el) return;
      e.preventDefault();
      if (location.hash !== u.hash) history.pushState(null, "", u.hash);
      lenis.scrollTo(el);
    });
  };
  document.head.appendChild(s);
})();

/* THIS WEEK'S SPECIAL. The office edits row 2 of the "Prime Lift Weekly
   Updates" Google Sheet (tab "This Week's Special", published to the web as
   CSV): A2 = the banner sentence, B2 = last day to show it. Empty A2 = no
   banner. Injected AFTER the 100svh hero so it costs nothing at first paint
   and never shifts visible layout. Fails silent; renders home page only. */
(function(){
  var hero = document.querySelector(".hero");
  if (!hero || !window.fetch) return;
  var CSV = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSwHQGTw88cR99Mj_Bg0OenyFiPZb3jVtatRpygtuOwA-KNqold2F6P98cgOLB9HEAM84YeSlQ8jCV2/pub?gid=1405683584&single=true&output=csv";
  /* 5-minute cache bucket: fresh enough for a weekly banner, kind to Google's edge */
  fetch(CSV + "&cb=" + Math.floor(Date.now() / 3e5), {cache: "no-store"})
    .then(function(r){ return r.ok ? r.text() : ""; })
    .then(function(t){
      var line = (t.split(/\r?\n/)[1] || "");
      /* first two CSV fields of the data row; handles quoted commas */
      var f = [], cur = "", q = false, i, c;
      for (i = 0; i < line.length && f.length < 2; i++) {
        c = line[i];
        if (q) { if (c === '"') { if (line[i+1] === '"') { cur += '"'; i++; } else q = false; } else cur += c; }
        else if (c === '"') q = true;
        else if (c === ",") { f.push(cur); cur = ""; }
        else cur += c;
      }
      f.push(cur);
      var text = (f[0] || "").trim(), until = (f[1] || "").trim();
      if (!text) return;
      if (until) {
        var end = null, m = until.match(/^(\d{1,2})[\/\-.](\d{1,2})(?:[\/\-.](\d{2,4}))?$/);
        if (m) {
          var y = m[3] ? (m[3].length === 2 ? 2000 + +m[3] : +m[3]) : new Date().getFullYear();
          end = new Date(y, +m[1] - 1, +m[2], 23, 59, 59);
          /* no year given and the date is months gone: they meant next year */
          if (!m[3] && (new Date() - end) > 90 * 864e5) end.setFullYear(y + 1);
        } else {
          var d = new Date(until);
          if (!isNaN(d)) { d.setHours(23, 59, 59, 0); end = d; }
        }
        if (end && new Date() > end) return;
      }
      var s = document.createElement("section"); s.className = "spx"; s.setAttribute("aria-label", "This week's special");
      var w = document.createElement("div"); w.className = "wrap spx-in";
      var k = document.createElement("span"); k.className = "spx-k"; k.textContent = "This Week";
      var b = document.createElement("span"); b.className = "spx-t"; b.textContent = text;
      var a = document.createElement("a"); a.className = "spx-cta"; a.href = "/book/"; a.textContent = "Book a Class ›";
      w.appendChild(k); w.appendChild(b); w.appendChild(a); s.appendChild(w);
      hero.parentNode.insertBefore(s, hero.nextSibling);
    })
    .catch(function(){});
})();
