/* Prime Lift — shared page script (generated by build.py). Nav, mobile menu,
   reveal-on-scroll, FAQ accordions and the sticky call bar for inner pages. */
(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const nav=$("#nav"), burger=$("#navBurger"), callbar=$("#callbar");
  const home=!!$(".hero");            /* the home page keeps its own scroll logic */

  if(burger){
    const setAcc=(acc,open)=>{ acc.classList.toggle("open",open); acc.querySelector(".macc-t").setAttribute("aria-expanded",open?"true":"false"); };
    burger.addEventListener("click",()=>{
      const open=document.body.classList.toggle("mnav-open");
      burger.setAttribute("aria-expanded",open?"true":"false");
      burger.setAttribute("aria-label",open?"Close menu":"Open menu");
      if(!open) $$(".macc.open").forEach(a=>setAcc(a,false));   /* collapse on close so it reopens tidy */
    });
    /* Courses / Academy accordions inside the mobile menu */
    $$(".macc-t").forEach(t=>t.addEventListener("click",()=>{ const acc=t.parentElement; setAcc(acc,!acc.classList.contains("open")); }));
    $$("#mnav a").forEach(a=>a.addEventListener("click",()=>{ document.body.classList.remove("mnav-open"); burger.setAttribute("aria-expanded","false"); }));
    document.addEventListener("keydown",e=>{ if(e.key==="Escape"&&document.body.classList.contains("mnav-open")) burger.click(); });
  }

  if(!home){
    /* no layout reads inside the handler: just scrollY, which is free */
    let ticking=false;
    function paint(){
      const y=window.scrollY;
      if(nav) nav.classList.toggle("stuck",y>40);
      if(callbar) callbar.classList.toggle("show",y>360);
      ticking=false;
    }
    window.addEventListener("scroll",()=>{ if(!ticking){ ticking=true; requestAnimationFrame(paint); } },{passive:true});
    paint();
  }

  /* reveal */
  const rv=$$(".rv");
  if("IntersectionObserver" in window){
    const io=new IntersectionObserver(es=>es.forEach(e=>{ if(e.isIntersecting){ e.target.classList.add("in"); io.unobserve(e.target); } }),{rootMargin:"0px 0px -8% 0px",threshold:.08});
    rv.forEach(el=>io.observe(el));
  } else rv.forEach(el=>el.classList.add("in"));

  /* FAQ accordions on inner pages (home renders its own) */
  $$("[data-faq]").forEach(host=>{
    host.addEventListener("click",e=>{
      const q=e.target.closest(".faq-q"); if(!q) return;
      const item=q.parentElement, a=item.querySelector(".faq-a"), open=item.classList.contains("open");
      $$(".faq-item",host).forEach(it=>{ it.classList.remove("open"); it.querySelector(".faq-a").style.maxHeight=null; it.querySelector(".faq-q").setAttribute("aria-expanded","false"); });
      if(!open){ item.classList.add("open"); a.style.maxHeight=a.scrollHeight+"px"; q.setAttribute("aria-expanded","true"); }
    });
  });
  window.addEventListener("resize",()=>{ $$(".faq-item.open .faq-a").forEach(a=>{ a.style.maxHeight="none"; const h=a.scrollHeight; a.style.maxHeight=h+"px"; }); });

  /* course pages: the "next start dates" strip is rendered at build time from
     SCHEDULE_RULES in build.py; recompute from today's date so it never goes
     stale between builds. Same rule: next N occurrences of the weekday, from
     tomorrow (booking closes the day before). */
  const MONS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], DOWS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"], SCHED={"closed":{"2026-09-07":"Labor Day"},"full":{}};
  const iso=d=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0");
  const bookable=(x,k)=>!SCHED.closed[iso(x)] && !((SCHED.full[iso(x)]||[]).some(f=>f===k||f==="*"));
  $$(".nd-row").forEach(row=>{
    const wd=+row.dataset.wd; if(isNaN(wd)) return;
    const key=row.dataset.book+":"+row.dataset.fmt, links=$$(".nd-date",row);
    const d=new Date(); d.setHours(0,0,0,0); d.setDate(d.getDate()+(+row.dataset.lead||1));
    while(d.getDay()!==wd) d.setDate(d.getDate()+1);
    const dates=[]; while(dates.length<links.length){ if(bookable(d,key)) dates.push(new Date(d)); d.setDate(d.getDate()+7); }
    links.forEach((a,i)=>{
      const x=dates[i];
      a.href="/book/?book="+row.dataset.book+"&fmt="+row.dataset.fmt+"&date="+iso(x);
      a.textContent=DOWS[x.getDay()]+", "+MONS[x.getMonth()]+" "+x.getDate();
    });
  });
})();

/* GHL live chat widget (Conversation AI). Loaded lazily so it never competes with
   first paint: first scroll / touch / pointer, or 6s idle, whichever comes first. */
(function(){
  if (window.__plChat) return; window.__plChat = 1;
  var done = false;
  function load(){
    if (done) return; done = true;
    var s = document.createElement("script");
    s.src = "https://widgets.leadconnectorhq.com/loader.js";
    s.setAttribute("data-resources-url", "https://widgets.leadconnectorhq.com/chat-widget/loader.js");
    s.setAttribute("data-widget-id", "6a935fa49f17bc64b3251340");
    document.body.appendChild(s);
    ["scroll","pointerdown","touchstart","keydown"].forEach(function(e){ window.removeEventListener(e, load); });
    lift();
  }
  /* On phones the sticky call bar owns the bottom 60px; keep the bubble above it.
     The widget's bubble lives in an open shadow root with inline bottom:20px, and
     the widget REWRITES that inline style every time the chat window closes, so
     setting it once is not enough (the bubble dropped back onto the Book button).
     A stylesheet inside the shadow root with !important beats the inline value
     for good; the offset rides on a CSS variable on the host element. */
  function lift(){
    var tries = 0;
    var cb = document.getElementById("callbar");
    var CSS = "#lc_text-widget,#lc_text-widget--btn{bottom:var(--pl-bottom,20px)!important}";
    function place(){
      var host = document.querySelector("chat-widget"), sr = host && host.shadowRoot;
      var box = sr && sr.getElementById("lc_text-widget"), btn = sr && sr.getElementById("lc_text-widget--btn");
      if (!box || !btn) { if (tries++ < 60) setTimeout(place, 500); return; }
      if (!sr.getElementById("pl-lift")) { var st = document.createElement("style"); st.id = "pl-lift"; st.textContent = CSS; sr.appendChild(st); }
      var mobile = window.innerWidth <= 900, up = mobile && cb && cb.classList.contains("show");
      host.style.visibility = (mobile && !up) ? "hidden" : "visible";
      host.style.setProperty("--pl-bottom", up ? "78px" : "20px");
      if (!host.__plObs) {
        /* if the widget ever rebuilds its shadow tree, put the stylesheet back */
        host.__plObs = new MutationObserver(function(){ if (!sr.getElementById("pl-lift")) place(); });
        host.__plObs.observe(sr, {childList:true});
      }
    }
    place();
    if (cb) new MutationObserver(place).observe(cb, {attributes:true, attributeFilter:["class"]});
    window.addEventListener("resize", place, {passive:true});
  }
  ["scroll","pointerdown","touchstart","keydown"].forEach(function(e){ window.addEventListener(e, load, {passive:true, once:true}); });
  setTimeout(load, 6000);
})();

/* LIVE SEATS. /.netlify/functions/seats counts open cards in the office's own
   Enrollment pipeline (one card = one seat, Lost frees it), so a class fills up
   on the site the moment the 8th student is booked online OR by phone. The
   static lists render first from CLOSED/FULL in build.py; this pass decorates
   every date link on the page (home band, course strips, class-dates tiles)
   and hands the data to /book/ through the pl:seats event. Fails silent. */
(function(){
  var CAP = 8, LOW = 3;
  function keyOf(a){
    var m = (a.getAttribute("href") || "").match(/[?&]book=([a-z]+)&(?:amp;)?fmt=([a-z]+)&(?:amp;)?date=(\d{4}-\d{2}-\d{2})/);
    return m ? m[1] + ":" + m[2] + ":" + m[3] : null;
  }
  function paint(data){
    var taken = data.taken || {}, cap = data.cap || CAP;
    document.querySelectorAll("a.ln-date, a.nd-date, a.date").forEach(function(a){
      var k = keyOf(a); if (!k) return;
      var left = cap - (taken[k] || 0);
      var tile = a.classList.contains("date"), seats = tile && a.querySelector(".seats");
      if (left <= 0) {
        a.classList.add("is-full"); a.setAttribute("aria-disabled", "true"); a.setAttribute("tabindex", "-1"); a.setAttribute("href", "#");
        if (seats) { seats.querySelector("b").textContent = "—"; seats.querySelector("span").textContent = "full"; }
        else if (!a.querySelector(".left")) a.insertAdjacentHTML("beforeend", '<span class="left"> · full</span>');
        return;
      }
      if (seats) {
        seats.querySelector("b").textContent = left; seats.querySelector("span").textContent = left === 1 ? "seat left" : "seats left";
        seats.classList.toggle("low", left <= LOW);
      } else if (left <= LOW && !a.querySelector(".left")) {
        a.insertAdjacentHTML("beforeend", '<span class="left"> · ' + left + " left</span>");
      }
    });
  }
  function go(){
    var url = "/.netlify/functions/seats";
    if (location.protocol === "file:" || /^(127\.0\.0\.1|localhost)$/.test(location.hostname) && location.port !== "8888") return;
    fetch(url, {cache: "no-cache"}).then(function(r){ return r.ok ? r.json() : null; }).then(function(d){
      if (!d || !d.taken) return;
      window.__plSeats = d;
      paint(d);
      document.dispatchEvent(new CustomEvent("pl:seats", {detail: d}));
    }).catch(function(){});
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", go); else go();
})();
