# -*- coding: utf-8 -*-
"""
Prime Lift Rigging Academy — site content.
Everything build.py renders comes from here. Facts only: prices, schedules,
policies and people were confirmed by the client (onboarding 8/20/26,
schedule 8/24/26). Do not add claims (pass rates, years founded, student
counts) that the client has not stated.
"""

BIZ = {
    "name": "Prime Lift Rigging Academy",
    "legal": "Prime Lift Rigging Academy LLC",
    "phone": "(361) 413-0160",
    "phone_raw": "+13614130160",
    "email": "primelift26@gmail.com",
    "street": "1605 US Highway 181 Frontage Rd, Suite A",
    "city": "Portland",
    "state": "TX",
    "zip": "78374",
    "hours": "Monday – Friday · 7:00 AM – 5:00 PM",
    "facebook": "https://www.facebook.com/profile.php?id=61591822862013",
    "tiktok": "https://www.tiktok.com/@primeliftacademy",
    "gmaps": "https://www.google.com/maps/place/?cid=16553214961176374110",
    "map_embed": "https://www.google.com/maps?q=1605+US+Highway+181+Frontage+Rd,+Portland,+TX+78374&output=embed",
    "lat": 27.8893523,
    "lng": -97.313445,
    "areas": ["Portland", "Corpus Christi", "Ingleside", "Gregory", "Aransas Pass",
              "Rockport", "Robstown", "Taft", "Sinton", "Kingsville"],
}

# ---------------------------------------------------------------- courses
COURSES = [
    {
        "id": "advanced", "slug": "advanced-rigger",
        "name": "Advanced Rigger",
        "cred": "NCCER Certified Advanced Rigger",
        "price": 1000, "was": 1700, "deposit": 200,
        "img": "img/card-rigger.jpg",
        "hero": "img/card-rigger.jpg",
        "hero_alt": "Instructor demonstrating a sling hitch on a load during an Advanced Rigger class",
        "kicker": "NCCER Certified Advanced Rigger",
        "h1": "Advanced Rigger<em>Certification</em>",
        "lede": "Four days of classroom and hands-on rigging in Portland, TX, then a written and practical test-out in the same building. Day, night or one weekend. $200 holds your seat.",
        "meta_title": "Advanced Rigger Certification (NCCER) in Portland, TX",
        "meta_desc": "NCCER Advanced Rigger certification near Corpus Christi. 4-day course, day or night, or a 3-day weekend express. Test out on-site. $1,000, $200 deposit.",
        "summary": "The Advanced Rigger course is for anyone who rigs loads for a living, or wants to. New hires get the foundation; experienced hands get the card that proves what they already know. You learn to plan a lift, calculate load weight and center of gravity, pick and inspect the right sling and hardware, control the load, and signal the crane, then you test out in our accredited testing room.",
        "learn": [
            "Advanced rigging principles and lift planning",
            "Load weight calculations and center of gravity",
            "Sling selection, hitch configurations and inspections",
            "Rigging hardware: shackles, hooks, spreader bars and below-the-hook devices",
            "Load control, tag lines and crane hand signals",
            "Written and hands-on practical test-out on the last day",
        ],
        "formats": [
            {"name": "Weekday Day Class", "when": "Mon – Thu", "time": "8:00 AM – 2:00 PM", "note": "Four days. Starts every Monday."},
            {"name": "Weekday Night Class", "when": "Mon – Thu", "time": "6:00 PM – 11:00 PM", "note": "Four nights. Built for day-shift crews.", "link": "/night-classes/"},
            {"name": "3-Day Weekend Express", "when": "Fri – Sun", "time": "8:00 AM – 5:00 PM", "note": "Done in one weekend. Starts every Friday.", "link": "/weekend-express/"},
        ],
        "who": [
            ("New hires", "No experience required. The course starts from the ground up and you leave with a credential that gets you through the gate."),
            ("Experienced riggers", "You already know the work. Get the NCCER card that puts it on paper for every contractor and turnaround in the country."),
            ("Recertification", "NCCER rigger credentials are good for five years. Coming due? See our recertification page."),
            ("Crews", "Companies book seats for up to 8 students per class. Call the office for group scheduling."),
        ],
        "faq": [
            ("How long is the Advanced Rigger course?", "Four days, Monday through Thursday, in either the day class (8:00 AM to 2:00 PM) or the night class (6:00 PM to 11:00 PM). The 3-Day Weekend Express runs Friday through Sunday, 8:00 AM to 5:00 PM."),
            ("Do I need experience to enroll?", "No. The course is built for both new and experienced riggers. Everything is taught from the ground up, and the hands-on portion uses real rigging hardware."),
            ("What does it cost?", "$1,000 during our current promotion, normally $1,700. A $200 deposit secures your seat and the remaining $800 is due before your class begins. Klarna, Afterpay, Zelle and in-house financing with no credit check are available."),
            ("Is the credential recognized nationally?", "Yes. You test out in our NCCER accredited assessment center and your credential is recorded on the NCCER Registry, which contractors across the country use to verify craft credentials."),
            ("How long is the certification good for?", "Five years from the date it is issued."),
            ("What should I bring?", "A government-issued photo ID for NCCER testing, something to write with, and work boots for the hands-on portion. Book early and we'll send study material so you can start before day one."),
        ],
    },
    {
        "id": "signal", "slug": "signal-person",
        "name": "Signal Person",
        "cred": "NCCER Certified Signal Person",
        "price": 1000, "was": None, "deposit": 200,
        "img": "img/card-signal.jpg",
        "hero": "img/card-signal.jpg",
        "hero_alt": "Rigger giving a hand signal from a personnel platform during a crane lift",
        "kicker": "NCCER Certified Signal Person",
        "h1": "Signal Person<em>Certification</em>",
        "lede": "Be the eyes and the voice of the lift. Two Fridays of classroom and hands-on practice in Portland, TX, then a written and practical test. $200 holds your seat.",
        "meta_title": "Signal Person Certification (NCCER) in Portland, TX",
        "meta_desc": "NCCER Signal Person certification near Corpus Christi. Two Fridays of hands-on training, crane hand signals, written and practical test on-site. $1,000.",
        "summary": "A qualified signal person is required on any lift where the operator can't see the load. This course teaches the standard hand signals, the voice and radio procedures that keep a lift moving safely, and the judgment to stop one. You practice signaling real movements, then test out written and hands-on.",
        "learn": [
            "Industry-standard crane hand signals",
            "Voice and radio communication on the lift",
            "Signal person responsibilities and when to stop the lift",
            "Working with the operator and the rigging crew",
            "Two days of classroom and hands-on practice",
            "Written and practical test, certification on completion",
        ],
        "formats": [
            {"name": "Two Fridays", "when": "Fridays", "time": "8:00 AM – 3:00 PM", "note": "Two days of training. Starts every Friday."},
        ],
        "who": [
            ("Riggers adding a credential", "Most Advanced Rigger students add Signal Person so they can fill either role on a crew."),
            ("Crane crews", "Refineries, plants, construction and shipyards all need a qualified signal person on the ground."),
            ("New to the trade", "No experience required. If you can learn the signals, you can earn the card."),
            ("Crews", "Companies book seats for up to 8 students per class. Call the office for group scheduling."),
        ],
        "faq": [
            ("How long is the Signal Person course?", "Two Fridays, 8:00 AM to 3:00 PM, with the written and practical test at the end."),
            ("What does it cost?", "$1,000. A $200 deposit secures your seat and the remaining $800 is due before class begins. Klarna, Afterpay, Zelle and in-house financing are available."),
            ("Do I need to be a rigger first?", "No. Signal Person stands on its own. Many students take it alongside Advanced Rigger, but it isn't a prerequisite."),
            ("Is the credential recognized nationally?", "Yes. Your NCCER Signal Person credential is recorded on the NCCER Registry."),
            ("What should I bring?", "A government-issued photo ID for NCCER testing, something to write with, and work boots for the hands-on portion."),
        ],
    },
]

ASSESSMENT = {
    "id": "assessment", "slug": "nccer-assessments",
    "name": "NCCER Assessments",
    "price": 150,
    "img": "img/card-assessment.jpg",
    "hero": "img/testing-room.jpg",
    "hero_alt": "Candidates taking a proctored NCCER assessment in the on-site testing room",
    "kicker": "NCCER Accredited Assessment Center",
    "h1": "Test Out.<em>Get The Card.</em>",
    "lede": "Already know the work? Skip the class. We proctor NCCER written and hands-on assessments in 36 crafts, Monday through Friday by appointment, one flat $150 per assessment.",
    "meta_title": "NCCER Assessments in Portland, TX · Test Out in 36 Crafts · $150",
    "meta_desc": "NCCER craft assessments near Corpus Christi: pipefitter, millwright, boilermaker, electrician, heavy equipment, HVAC, plumber and more. $150 flat, proctored on-site.",
    "faq": [
        ("What is an NCCER assessment?", "A proctored written assessment of what you know about your craft, with a hands-on performance verification where the craft calls for one. Pass, and your credential is recorded on the NCCER Registry, which contractors use to verify craft skills."),
        ("Do I have to take a class first?", "No. Assessments are for people who already have the field experience. If you want training first, see our Advanced Rigger and Signal Person courses."),
        ("What does it cost?", "$150 per assessment, one flat price across every craft we assess. Paid in full when you book."),
        ("When can I test?", "Monday through Friday, 8:00 AM to 5:00 PM, by appointment. Book online or call the office. Bringing a crew? Call and we'll block the testing room."),
        ("What do I bring?", "A government-issued photo ID. NCCER requires it before you can sit for any assessment."),
        ("What if I don't pass?", "Talk to the office about a retest date. Our instructors can also point you to the areas to study."),
    ],
}

CRAFT_GROUPS = [
    ("Rigging & Lifting", "rigging"),
    ("Heavy Equipment Operation", "heo"),
    ("Pipe, Mechanical & Millwright", "mech"),
    ("Electrical & Instrumentation", "ei"),
    ("Boilermaker & Pressure Equipment", "boiler"),
    ("Structural, Carpentry & Concrete", "struct"),
    ("Finishing, Insulation & Coatings", "finish"),
    ("Cleaning & Support Trades", "support"),
]

# slug, name, group, blurb (what the craft does), covers (what the assessment
# measures), tests (True = there is a hands-on performance component we advertise)
CRAFTS = [
    ("boilermaker-pressure-vessel", "Boilermaker (Pressure Vessel)", "boiler",
     "Pressure-vessel boilermakers fabricate, erect and repair boilers, tanks, vessels and exchangers in refineries, chemical plants and power stations.",
     "vessel components and nomenclature, layout and fit-up, rigging vessel sections, tube work, welding-related tasks, hydrostatic testing and boilermaker safety."),
    ("commercial-carpenter", "Commercial Carpenter", "struct",
     "Commercial carpenters build the forms, framing, interior and exterior systems on commercial construction projects.",
     "blueprint reading, layout, framing, concrete formwork, interior finish systems, doors and hardware, and jobsite safety."),
    ("commercial-electrician", "Commercial Electrician", "ei",
     "Commercial electricians install and maintain the power, lighting and control systems in commercial buildings.",
     "the National Electrical Code, conductors and raceways, boxes and fittings, branch circuits and feeders, motors and controls, and electrical safety."),
    ("concrete-finisher", "Concrete Finisher", "struct",
     "Concrete finishers place, screed, float, trowel and cure concrete slabs, walls and structures.",
     "concrete properties and admixtures, placing and consolidating, screeding and floating, troweling and finishing, joints, curing and repair."),
    ("drywall-mechanic", "Drywall Mechanic", "finish",
     "Drywall mechanics hang, tape and finish gypsum board on walls and ceilings in commercial and industrial buildings.",
     "board types and fasteners, layout and hanging, taping and finishing levels, corner beads and trims, and material handling safety."),
    ("heavy-equipment-operator-backhoe", "Heavy Equipment Operator: Backhoe", "heo",
     "Backhoe operators dig trenches, set pipe, backfill and load material on construction and utility jobs.",
     "backhoe controls and pre-operation inspection, trenching and excavation, loading, grade checking, and safe operation around utilities and workers."),
    ("heavy-equipment-operator-compaction-equipment", "Heavy Equipment Operator: Compaction Equipment", "heo",
     "Compaction operators run rollers and compactors to build stable subgrades, base courses and asphalt mats.",
     "compactor types and pre-operation inspection, lift thickness and pattern, soil and asphalt compaction, and safe operation on grades and near workers."),
    ("heavy-equipment-operator-dozer", "Heavy Equipment Operator: Dozer", "heo",
     "Dozer operators clear, cut, push and grade earth on site preparation and heavy civil projects.",
     "dozer controls and inspection, blade types, cutting and pushing, rough and finish grading, slope work, and safe operation."),
    ("heavy-equipment-operator-excavator", "Heavy Equipment Operator: Excavator", "heo",
     "Excavator operators dig foundations, trenches and ponds, and load trucks on construction and industrial sites.",
     "excavator controls and inspection, trenching and mass excavation, loading, grade control, attachments, and safe operation near utilities."),
    ("heavy-equipment-operator-forklift", "Heavy Equipment Operator: Forklift", "heo",
     "Forklift operators move, stack and stage material in plants, laydown yards and warehouses.",
     "forklift types and pre-operation inspection, load capacity and stability, picking and placing loads, traveling with a load, and OSHA-aligned safe operation."),
    ("heavy-equipment-operator-loader", "Heavy Equipment Operator: Loader", "heo",
     "Loader operators load trucks, move aggregate and stockpile material on construction and plant sites.",
     "loader controls and inspection, bucket loading and carrying, truck loading, stockpiling, and safe operation on uneven ground."),
    ("heavy-equipment-operator-motor-grader", "Heavy Equipment Operator: Motor Grader", "heo",
     "Motor grader operators cut and finish subgrade, base and road surfaces to grade and crown.",
     "grader controls and inspection, blade positioning, cutting and spreading, ditching, finish grading to stakes or GPS, and safe operation."),
    ("heavy-equipment-operator-off-road-dump-truck", "Heavy Equipment Operator: Off-Road Dump Truck", "heo",
     "Off-road dump truck operators haul earth and aggregate on mine, quarry and heavy civil sites.",
     "articulated and rigid haul truck inspection, loading and dumping procedures, haul-road operation, backing and spotting, and safe operation on grades."),
    ("heavy-equipment-operator-scraper", "Heavy Equipment Operator: Scraper", "heo",
     "Scraper operators cut, haul and spread earth over long distances on mass grading projects.",
     "scraper controls and inspection, loading with and without a push, hauling, spreading and finishing, and safe operation."),
    ("heavy-equipment-operator-skid-steer", "Heavy Equipment Operator: Skid Steer", "heo",
     "Skid steer operators handle grading, loading, demolition and attachment work in tight spaces.",
     "skid steer controls and inspection, attachments, loading and grading, operating on slopes and in confined areas, and safe operation."),
    ("hvac-technician", "HVAC Technician", "mech",
     "HVAC technicians install, service and troubleshoot heating, ventilation, air conditioning and refrigeration systems.",
     "refrigeration cycle and components, electrical circuits and controls, air distribution, system installation and startup, troubleshooting, and EPA-related refrigerant handling."),
    ("hydroblasting-technician", "Hydroblasting Technician", "support",
     "Hydroblasting technicians use high-pressure water to clean exchangers, vessels, piping and surfaces during turnarounds.",
     "high-pressure water jetting equipment, hose and lance handling, pressure and flow control, exclusion zones and PPE, and industrial cleaning safety."),
    ("industrial-boilermaker-exchanger", "Industrial Boilermaker (Exchanger)", "boiler",
     "Exchanger boilermakers pull, clean, re-tube and re-bundle heat exchangers in refinery and petrochemical maintenance.",
     "exchanger types and components, bundle pulling and rigging, gasket and flange work, tube rolling and plugging, hydrotesting, and boilermaker safety."),
    ("industrial-boilermaker-maintenance", "Industrial Boilermaker (Maintenance)", "boiler",
     "Maintenance boilermakers repair boilers, vessels, tanks and stacks in operating plants.",
     "boiler and vessel components, inspection and repair methods, rigging and fit-up, welding-related tasks, testing, and confined-space and hot-work safety."),
    ("industrial-carpenter", "Industrial Carpenter", "struct",
     "Industrial carpenters build formwork, scaffolds, decking and temporary structures in plants and heavy construction.",
     "blueprint reading and layout, concrete formwork, framing, scaffold and temporary structures, and jobsite safety."),
    ("industrial-electrician", "Industrial Electrician", "ei",
     "Industrial electricians install and maintain power distribution, motors and controls in plants and refineries.",
     "the National Electrical Code, conduit and cable systems, motors and motor controls, transformers and distribution, hazardous-location wiring, and electrical safety."),
    ("industrial-insulator", "Industrial Insulator", "finish",
     "Industrial insulators apply insulation and jacketing to piping, vessels and equipment.",
     "insulation materials and selection, pipe and vessel insulation, metal jacketing and fabrication, vapor barriers, and safe work around hot and cold systems."),
    ("industrial-ironworker", "Industrial Ironworker", "struct",
     "Industrial ironworkers erect structural steel, set equipment and install grating, handrail and platforms.",
     "structural steel erection, bolting and torquing, rigging and connecting, layout and plumbing, grating and handrail, and fall protection."),
    ("industrial-maintenance-ei-technician", "Industrial Maintenance E&I Technician", "ei",
     "Electrical and Instrumentation technicians keep plant power, control and measurement systems running.",
     "electrical troubleshooting, motor controls, instrumentation loops, calibration, control valves, and electrical and process safety."),
    ("industrial-maintenance-mechanic", "Industrial Maintenance Mechanic", "mech",
     "Industrial maintenance mechanics repair and align pumps, compressors, gearboxes and rotating equipment.",
     "precision measuring, bearings and seals, shaft alignment, pumps and compressors, lubrication, and mechanical safety."),
    ("industrial-maintenance-support-mechanic", "Industrial Maintenance Support Mechanic", "mech",
     "Support mechanics assist maintenance crews with equipment disassembly, rigging, parts handling and reassembly.",
     "hand and power tools, fasteners and torque, basic rigging, equipment disassembly and reassembly, and maintenance safety."),
    ("industrial-millwright", "Industrial Millwright", "mech",
     "Millwrights install, align and maintain machinery: pumps, turbines, conveyors, gearboxes and compressors.",
     "precision measurement, leveling and alignment, bearings and couplings, conveyors and gear drives, machinery installation, and millwright safety."),
    ("industrial-painter", "Industrial Painter", "finish",
     "Industrial painters prepare and coat steel, piping and structures to protect them from corrosion.",
     "surface preparation and abrasive blasting, coating types and mixing, spray and brush application, inspection and film thickness, and coatings safety."),
    ("industrial-pipefitter", "Industrial Pipefitter", "mech",
     "Pipefitters lay out, fabricate, install and test piping systems in refineries, plants and power stations.",
     "pipe and fitting identification, blueprint and isometric reading, layout and takeoffs, threaded, socket-weld and butt-weld fit-up, flanges and bolting, pipe hangers, and hydrotesting."),
    ("instrumentation-fitter", "Instrumentation Fitter", "ei",
     "Instrumentation fitters install tubing, instruments and supports for process measurement and control.",
     "tubing bending and fitting, instrument mounting and supports, impulse lines, process connections, and instrument installation safety."),
    ("instrumentation-technician", "Instrumentation Technician", "ei",
     "Instrumentation technicians calibrate, troubleshoot and maintain the instruments that measure and control a process.",
     "pressure, level, flow and temperature instruments, calibration, control loops and valves, transmitters and signals, and loop troubleshooting."),
    ("mason", "Mason", "struct",
     "Masons lay brick, block and stone for walls, structures and industrial refractory work.",
     "masonry materials and mortar, layout and leveling, laying units to the line, reinforcing and anchoring, and masonry safety."),
    ("offshore-maintenance-mechanic", "Offshore Maintenance Mechanic", "mech",
     "Offshore maintenance mechanics keep rotating and process equipment running on platforms and vessels.",
     "pumps and compressors, bearings and alignment, hydraulics, preventive maintenance, and offshore safety practices."),
    ("plumber", "Plumber", "mech",
     "Plumbers install and repair water supply, drain-waste-vent and gas piping in commercial and industrial buildings.",
     "plumbing codes, DWV and water supply systems, pipe materials and joining, fixtures, backflow prevention, and plumbing safety."),
    ("reinforcing-iron-rebar-worker", "Reinforcing Iron & Rebar Worker", "struct",
     "Rebar workers place and tie the reinforcing steel that gives concrete its strength.",
     "bar identification and placing drawings, cutting and bending, tying and splicing, chairs and spacing, and rebar safety."),
    ("scaffold-builder", "Scaffold Builder", "struct",
     "Scaffold builders erect and dismantle the frame, tube-and-clamp and system scaffolds every turnaround runs on.",
     "scaffold components and types, foundations and bracing, planking and access, tie-ins, inspection tagging, and fall protection."),
]

# ------------------------------------------------------------- instructors
PEOPLE = [
    {
        "slug": "andres-herrera", "name": "Andres Herrera",
        "role": "Co-Founder · NCCER Practical Examiner",
        "short": "Director / Manager",
        "img": "img/team-andres.jpg",
        "alt": "Andres Herrera working from a personnel platform on a refinery lift",
        "teaches": ["advanced-rigger", "signal-person", "nccer-assessments"],
        "bio": [
            "After years of hands-on field experience, Andres and his business partner built Prime Lift to help craft professionals earn the credentials that move their careers.",
            "As an NCCER Practical Examiner he runs the hands-on training and the test-outs, with a hard focus on safety and jobsite reality. Students know him as Andy, and the reviews say the same thing over and over: he makes sure you understand it before the class moves on.",
        ],
        "meta_desc": "Andres Herrera, co-founder of Prime Lift Rigging Academy and NCCER Practical Examiner. Runs hands-on rigging training and NCCER test-outs in Portland, TX.",
    },
    {
        "slug": "juan-meza", "name": "Juan Meza",
        "role": "Director",
        "short": "Director / Manager",
        "img": "img/team-juan.jpg",
        "alt": "Juan Meza on the tracks of a Liebherr crawler crane at a jobsite",
        "teaches": ["advanced-rigger", "nccer-assessments"],
        "bio": [
            "Juan built his career through years of hands-on industry experience and now leads the academy's programs.",
            "He's the one making sure every student leaves with the skills, the confidence and the foundation to build a real career in the trades, and that the schedule works around the shifts people actually work.",
        ],
        "meta_desc": "Juan Meza, Director at Prime Lift Rigging Academy in Portland, TX. Leads the academy's NCCER rigging and assessment programs.",
    },
    {
        "slug": "frank-torres", "name": "Frank Torres",
        "role": "Advanced Rigging Instructor",
        "short": "Advanced Rigging Instructor",
        "img": "img/team-frank.jpg",
        "alt": "Frank Torres at a heavy lift jobsite with crawler cranes",
        "teaches": ["advanced-rigger", "signal-person"],
        "bio": [
            "Frank is an NCCER Advanced Rigger and Signal Person with more than 10 years of crane and rigging experience, and he brings all of it into the classroom.",
            "He genuinely wants every student to pass. Don't be afraid to ask him to explain something twice; take advantage of what he knows.",
        ],
        "meta_desc": "Frank Torres, Advanced Rigging Instructor at Prime Lift Rigging Academy. NCCER Advanced Rigger and Signal Person with 10+ years of crane and rigging experience.",
    },
]

# ----------------------------------------------------------------- reviews
REVIEWS = [
    {"who": "Ryan P", "src": "google", "stars": 5,
     "text": "Awesome experience, a lot of knowledge on all rigging, from forklifts to rigging I've never even seen or heard of. Great teachers and instructors, Frank and Andy will make sure you understand before moving on to the next lesson. 5/5 stars, highly recommend to any and everybody wanting to get their certifications."},
    {"who": "Joshua Fonseca", "src": "google", "stars": 5,
     "text": "A lot of one-to-one explanation. All questions will be answered directly to you; the teacher will sit there and go over it as many times as you need until you understand. Definitely recommend."},
    {"who": "Viko Ledesma", "src": "facebook",
     "text": "All you need to know, they will teach and guide you thru the process of getting your NCCER certification!"},
    {"who": "Arturo Duran Jr.", "src": "facebook",
     "text": "It's a very great class, a lot of good information, and the instructor did an awesome job explaining the information."},
    {"who": "Michael Cervantes", "src": "facebook",
     "text": "Great exercise, very professional. I recommend others to go through Prime Lift Rigging."},
]

# --------------------------------------------------------------------- FAQ
FAQ = [
    ("How long does the Advanced Rigger course take?",
     "Four days, Monday through Thursday. Day classes run 8:00 AM to 2:00 PM and night classes run 6:00 PM to 11:00 PM, so you can keep working either shift. If you can't take time off during the week at all, the 3-Day Weekend Express runs Friday through Sunday, 8:00 AM to 5:00 PM, and you walk out certified after one weekend."),
    ("What does it cost and what do I pay today?",
     "Advanced Rigger is $1,000 during our current promotion, normally $1,700. Signal Person is $1,000. A $200 deposit secures your seat and the remaining $800 is due before your class begins. NCCER assessments are $150 flat for any of our 36 crafts, paid in full at registration."),
    ("What if I can't pay the whole thing up front?",
     "You have options. Klarna and Afterpay are available; both cover the full $1,000 up front and then split it into payments for you, so those are pay-in-full options at checkout rather than the $200 deposit. If you don't qualify for either, we offer in-house financing with no credit check: as little as $200 down and payments leading up to your course date. We also take Zelle if you'd rather register that way. Either way, your course can't begin until the balance is paid in full."),
    ("Is this a real NCCER certification?",
     "Yes. We're an NCCER Accredited Training and Assessment Center, so you train and test out in the same building and your credential is recorded on the NCCER national registry, recognized on jobsites across the country."),
    ("Do I need experience to take the Advanced Rigger course?",
     "No experience required. The course is designed for both new and experienced riggers. We cover advanced rigging principles, load weight calculations, center of gravity, sling selection and inspection, hitch configurations, load control, lift planning and crane hand signals from the ground up."),
    ("What's included in the course?",
     "Classroom instruction, hands-on practice with real rigging hardware, your written and practical assessment, and your NCCER certification upon successful completion. Book early and we'll get study material to you so you can start before day one."),
    ("Can I test out without taking a class?",
     "Yes. As an accredited NCCER Assessment Center we proctor written and hands-on assessments in 36 crafts, from pipefitter and millwright to forklift and excavator, for $150 per assessment. Monday through Friday, 8:00 AM to 5:00 PM, by appointment."),
    ("How long is the credential good for?",
     "NCCER rigger credentials are valid for five years from the date they're issued. When yours is coming due, call the office and we'll schedule your recertification."),
    ("What is your deposit and reschedule policy?",
     "A $200 deposit is required to secure your spot. This deposit is non-refundable. However, you are allowed one reschedule as long as at least 48 hours' notice is provided. Rescheduling requests made with less than 48 hours' notice will result in the loss of your deposit."),
    ("Can you certify my whole crew?",
     "Yes. We take company bookings for up to 8 students at a time, here at our Portland training center. Call the office at (361) 413-0160 and ask for group scheduling and we'll work around your turnaround schedule."),
    ("Do you offer training in Spanish?",
     "Not at this time. All classes and assessments are taught and proctored in English."),
    ("Where are you located?",
     "1605 US Highway 181 Frontage Rd, Suite A, in Portland, Texas, minutes from Corpus Christi, Ingleside and Gregory. Office hours are Monday through Friday, 7:00 AM to 5:00 PM, though hours vary during class weeks."),
]

# ------------------------------------------------------------- financing
FINANCING = [
    ("Deposit & Balance", "$200 holds your seat today by card. The remaining $800 is due before your class starts, and you can pay it online, in the office, or on a schedule.", "Most students"),
    ("Klarna or Afterpay", "Split the cost into scheduled payments. Both pay the full $1,000 at checkout and then break it up for you, so choose Klarna or Afterpay on the checkout screen instead of the $200 deposit.", "Instant decision"),
    ("In-House Financing", "Don't qualify for Klarna or Afterpay? Start with as little as $200 down and make payments leading up to your class date. No credit check. Your course begins once the balance is paid in full.", "No credit check"),
    ("Zelle", "Prefer Zelle? Pick In-House on the booking screen and note it, or message us on Facebook or email the office and we'll register you manually.", "primelift26@gmail.com"),
    ("Employer Paying", "Company covering it? Choose \"My employer is paying\" on the booking form and the office will coordinate the invoice with them. Crews of up to 8 per class.", "Group bookings"),
]
